#!/bin/sh -e

case "$1" in

install)
    ;;

upgrade)
    if [ -f /opt/yaffas/etc/ssl/certs/org/default.crt ]; then
        cp /opt/yaffas/etc/ssl/certs/org/default.* /opt/yaffas/var/
    fi
    ;;

abort-upgrade)
    ;;   

*)
    echo "preinst called with unknown argument '$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
