#!/usr/bin/make -f
MODULE=translations

include ../../../Makefile.common

clean:

install:
	mkdir -p $(DESTDIR)/$(YAFFAS_SHARE)/yaffas-lang
	cp translations/lang/* $(DESTDIR)/$(YAFFAS_SHARE)/yaffas-lang/
