#! /bin/sh
set -e

case "$1" in
  purge)
    # restore configuration files
    # and remove our configuration files
	for CFG in /etc/zarafa/*.cfg.yaffassave; do
		mv -f $CFG ${CFG/.yaffassave/}
	done
	if [ -e /etc/apache2/sites-available/zarafa-webaccess-ssl.yaffassave ]; then
		mv -f /etc/apache2/sites-available/zarafa-webaccess-ssl.yaffassave /etc/apache2/sites-available/zarafa-webaccess-ssl
	fi

    ;;
  *)
     exit 0;;
esac

exit 0

