include ../../../Makefile.common

DESTDIR ?= /

clean:

install:
	mkdir -p $(DESTDIR)/$(YAFFAS_WEBMIN)/theme-core
	mkdir -p $(DESTDIR)/$(YAFFAS_WEBMIN)/images
	cp -a theme-core/* $(DESTDIR)/$(YAFFAS_WEBMIN)/theme-core
