include ../../../Makefile.common

DESTDIR ?= /

clean:

install:
	mkdir -p $(DESTDIR)/$(YAFFAS_WEBMIN)/yaffastheme
	mkdir -p $(DESTDIR)/$(YAFFAS_WEBMIN)/images
	cp -a yaffastheme/* $(DESTDIR)/$(YAFFAS_WEBMIN)/yaffastheme
