include ../../../Makefile.common

DESTDIR ?= /

clean:

install:
	mkdir -p $(DESTDIR)/$(YAFFAS_WEBMIN)/yui/assets/skins
	mkdir -p $(DESTDIR)/$(YAFFAS_WEBMIN)/zadmintheme
	mkdir -p $(DESTDIR)/$(YAFFAS_WEBMIN)/images
	cp -a yui/* $(DESTDIR)/$(YAFFAS_WEBMIN)/yui/assets/skins
	cp -a zadmintheme/* $(DESTDIR)/$(YAFFAS_WEBMIN)/zadmintheme
