include ../../../Makefile.common
DESTDIR ?= /
NTROOTDIR=mkntpwd/

dummy:

install:

	mkdir -p $(DESTDIR)/$(YAFFAS_PREFIX)/share
	cp -r share/yaffas-security $(DESTDIR)/$(YAFFAS_PREFIX)/share

clean:

