#!/bin/sh
echo Starting Webmin server in /opt/yaffas/webmin
trap '' 1
LANG=
export LANG
#PERLIO=:raw
unset PERLIO
export PERLIO
PERLLIB=/opt/yaffas/lib/perl5
export PERLLIB
exec '/opt/yaffas/webmin/miniserv.pl' /opt/yaffas/etc/webmin/miniserv.conf
